version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: iot-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: iot_phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iot-php-apache
    volumes:
      - .:/var/www/html
    ports:
      - "8002:80"
    depends_on:
      - db

volumes:
  db-data:
